### ISSUE TITLE
Problem with json_parameter_file

### ISSUE THREAD

**Issue by aknijn** [phac-nml/irida-galaxy-importer#1]
I'm trying to get the importer to work with our Galaxy cluster, however the imports fail. Galaxy (version 16.01) and Irida (version 0.13.4) were installed according to the documentation at irida.corefacility.ca and are working. When I use the irida-galaxy-importer (commit 34c9e65) inside Galaxy, I get correctly redirected to Irida. Selecting a Projects sample for "send to Galaxy", I get redirected back to Galaxy as expected and two jobs are activated. Unfortunately, after a minute or so, both jobs fail with the following error: 
AttributeError: IridaImport instance has no attribute 'uploaded_files_log'. 

In the log file, the error is more clear:
    json_params_dict = json.loads(param_dict['json_params'])
KeyError: 'json_params'

And in fact, looking at the json_parameter_file, the key json_params is missing:
[json_parameter_file.txt](https://github.com/phac-nml/irida-galaxy-importer/files/606557/json_parameter_file.txt)
(The file was slightly modified for privacy reasons)
Do you have any idea why this is happening, did I miss some requirement in either Galaxy or Irida?

**Comment by tom114** [comment]
It could be an issue in the javascript which compiles the list of samples to send.  Can you open the developer tools in your browser (Right click -> Inspect or Inspect Element) and open the console in that view to see if any javascript errors are thrown when going through the export process?

**Comment by aknijn** [comment]
Thank you for your fast reply. I don't see any javascript errors during the process, the only message is the following: JQMIGRATE: Logging is active                      libs.bundled.js:70:470

**Comment by aknijn** [comment]
Maybe I can add some information. Debugging the code, in Galaxy a Warning was raised with respect to SSL:  _InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail._ Eliminating the problem, the error message in Galaxy changed somewhat, adding the JSON file to it.
Both servers are reached through SSL connections but when selecting _Upload samples in_ Irida, an security warning shows up saying that the POST action is sent over an unencrypted connection. In your opinion, could this cause the JSON file to be incomplete?

**Comment by ericenns** [comment]
Here is an example of what a good json file should look like [sample.json](https://github.com/phac-nml/irida-galaxy-importer/blob/ad645b82433a32c5f3d9130cafc9219ba64a64b0/irida_import/sample.json).

Your file as you pointed out is missing the json_params entry. The json_params entry contains the json payload from the IRIDA server which tells the IRIDA Galaxy Importer which samples to import, data library to create, and the user who should have access to these samples, ... etc.

I am unsure why your missing this, it may have to do with the SSL but I don't think that is likely. It seems that there might be an issue on the IRIDA side of things.

**Comment by ericenns** [comment]
To do some further debugging can you use google-chrome and open the console by hitting 'F12', then can you change to the 'Network' tab and check 'Preserve Log'. After that is done can you go through the steps of importing data into Galaxy from IRIDA. After that is done can you look for a entry with the name 'tool_runner?tool_id=irida_import&runtool_btn=Execute', select it and look at the headers under Form Data. If it is working correctly you should see something like:

    json_params:{"_embedded":{"library":{"name":"Test"},"user":{"email":"test@spam4.me"},"addtohistory":true,"makepairedcollection":true,"oauth2":{"code":"BLAH","redirect":"/irida/galaxy/auth_code"},"samples":[{"name":"Sample 1","_links":{"self":{"href":""}},"_embedded":{"sample_files":[{"_links":{"self":{"href":"http://irida.local/irida/api/projects/1/samples/1"}}}]}}]}}

Note: The example data has been edited for privacy

**Comment by aknijn** [comment]
The sample.json is very useful, thank you for that. Following your debugging advice, I find that the JSON part gets POSTed:
`json_params:{"_embedded":{"library":{"name":"Project as Galaxy-nnnnn.sssss@dddd.eee"},"user":{"email":"nnnnn.sssss@dddd.eee"},"addtohistory":true,"makepairedcollection":true,"oauth2":{"code":"S3wu6v","redirect":"/irida/galaxy/auth_code"},"samples":[{"name":"Test_upload_sample","_links":{"self":{"href":""}},"_embedded":{"sample_files":[{"_links":{"self":{"href":"http://xxxx.dddd.eee/irida/api/projects/2/samples/3"}}}]}}]}}`
But somehow it doesn't get inserted into the file. 
In order to exclude problems due to SSL, I will now allow http unencrypted connections to both systems and see if that resolves the problem.

**Comment by aknijn** [comment]
Dropping SSL, resolves the problem with the JSON file as the json_params part is now included:
`{"param_dict": {"__datatypes_config__": "/xxxxxx/yyyyyyy/galaxy-dist/database/tmp/tmp6KO4Bd", "__get_data_table_entry__": "<function get_data_table_entry at 0xbd40758>", "userId": "1", "userEmail": "nnnnn.sssss@dddd.eee", "dbkey": "?", "GALAXY_DATA_INDEX_DIR": "/xxxxxx/yyyyyyy/galaxy-dist/tool-data", "__admin_users__": "nnnnn.sssss@dddd.eee,irida@dddd.eee,workflow@dddd.eee", "__user__": "galaxy.model:User", "input": "<function input at 0xbd407d0>", "json_params": "{\"_embedded\":{\"library\":{\"name\":\"Project as Galaxy-nnnnn.sssss@dddd.eee\"},\"user\":{\"email\":\"nnnnn.sssss@dddd.eee\"},\"addtohistory\":true,\"makepairedcollection\":true,\"oauth2\":{\"code\":\"ohWKSt\",\"redirect\":\"/irida/galaxy/auth_code\"},\"samples\":[{\"name\":\"Test_upload_sample\",\"_links\":{\"self\":{\"href\":\"\"}},\"_embedded\":{\"sample_files\":[{\"_links\":{\"self\":{\"href\":\"http://irida.dddd.eee/irida/api/projects/2/samples/3\"}}}]}}]}}", "__app__": "galaxy.app:UniverseApplication", "__user_email__": "nnnnn.sssss@dddd.eee", "GALAXY_DATATYPES_CONF_FILE": "/xxxxxx/yyyyyyy/galaxy-dist/database/tmp/tmp6KO4Bd", "__user_name__": "nnnnn-sssss", "runtool_btn": "Execute", "__tool_directory__": "/xxxxxx/yyyyyyy/galaxy-dist/tools/irida_import", "__new_file_path__": "/xxxxxx/yyyyyyy/galaxy-dist/database/tmp", "__user_id__": "1", "GALAXY_ROOT_DIR": "/xxxxxx/yyyyyyy/galaxy-dist", "__tool_data_path__": "/xxxxxx/yyyyyyy/galaxy-dist/tool-data", "__root_dir__": "/xxxxxx/yyyyyyy/galaxy-dist", "output": "/xxxxxx/yyyyyyy/galaxy-dist/database/files/066/dataset_66307.dat", "log_file": "/xxxxxx/yyyyyyy/galaxy-dist/database/files/066/dataset_66306.dat", "chromInfo": "/xxxxxx/yyyyyyy/galaxy-dist/tool-data/shared/ucsc/chrom/?.len"}, "output_data": [{"extra_files_path": "/xxxxxx/yyyyyyy/galaxy-dist/database/job_working_directory/046/46692/dataset_66307_files", "ext": "auto", "out_data_name": "output", "hda_id": 63445, "file_name": "/xxxxxx/yyyyyyy/galaxy-dist/database/files/066/dataset_66307.dat", "dataset_id": 66307}, {"extra_files_path": "/xxxxxx/yyyyyyy/galaxy-dist/database/job_working_directory/046/46692/dataset_66306_files", "ext": "txt", "out_data_name": "log_file", "hda_id": 63444, "file_name": "/xxxxxx/yyyyyyy/galaxy-dist/database/files/066/dataset_66306.dat", "dataset_id": 66306}], "job_config": {"GALAXY_ROOT_DIR": "/xxxxxx/yyyyyyy/galaxy-dist", "TOOL_PROVIDED_JOB_METADATA_FILE": "galaxy.json", "GALAXY_DATATYPES_CONF_FILE": "/xxxxxx/yyyyyyy/galaxy-dist/database/tmp/tmp6KO4Bd"}}`
And the jobs finishes without errors, exporting the samples to Galaxy! Do you have some idea how I could reintroduce SSL?

**Comment by ericenns** [comment]
When you configured the tool, did you setup the galaxy url to include https instead of http?

Did you also change the OAUTH setting as described [here](https://github.com/phac-nml/irida-galaxy-importer#configuring-the-tool).

**Comment by aknijn** [comment]
Yes, the Galaxy url was setup with https. I also had changed the setting of OAUTHLIB_INSECURE_TRANSPORT to 0. The strange thing is that I didn't change it for the test without SSL and it worked.

**Comment by aknijn** [comment]
I did some more tests and found that the export works if Galaxy is without SSL and Irida with, but it fails if Galaxy is with SSL and Irida without.

**Comment by aknijn** [comment]
Do you have any idea why Irida redirects the response towards galaxyCallbackUrl as defined in irida_import.xml but added to the Galaxy url in http, even if the galaxy_url parameter in config.ini is set with https?

**Comment by tom114** [comment]
Hi again.  Sorry for the delay, we're still looking at this issue.  Can you tell us what the full request URL is from Galaxy when it first connects to IRIDA?  So this would be what is in the URL string right after clicking `Get Data -> IRIDA server`.  It would look something like:

```
http://yourhost/projects?galaxyClientID=webClient&GALAXY_URL=http%3A//yourgalaxyhost/tool_runner%3Ftool_id%3Dirida_import&galaxyCallbackUrl=http%3A//yourgalaxyhost/tool_runner%3Ftool_id%3Dirida_import%26runtool_btn%3DExecute&appName=Galaxy
```

**Comment by aknijn** [comment]
No problem for the delay, I appreciate the time you're spening on this. Actually the URL string looks quite strange:
`https://IRIDA-HOST/irida/projects?galaxyClientID=galaxy-client&GALAXY_URL=http%3A//GALAXY-HOST/tool_runner%3Ftool_id%3Dirida_import&galaxyCallbackUrl=http%3A//GALAXY-HOSThttps%3A//GALAXY-HOST/tool_runner%3Ftool_id%3Dirida_import%26runtool_btn%3DExecute&appName=Galaxy`

**Comment by ericenns** [comment]
So me and @tom114 did some debugging yesterday and both the GALAXY_URL and galaxyCallbackUrl are generated by galaxy and not the irida-galaxy-importer tool. Note: on IRIDA we use the galaxyCallbackUrl to submit the form too.

There is a galaxy url setting in the config.ini for the tool, but that is for the tool to communicate with galaxy after it gets the json file from IRIDA.

I can create an issue on the galaxy project github page if you want, what version of galaxy are you using?

**Comment by tom114** [comment]
Hi again.  While we wait for the issue @ericenns reported to galaxy to be addressed, he made a small change to our importer to use the address given in the config file rather than what's sent by galaxy.  Would you like to test it out to validate whether it's working for your install? 

I've pushed up a new branch to https://github.com/phac-nml/irida-galaxy-importer/tree/https_fixes.
You'll need to either check out the full branch, or replace the files `irida_import.py` and `irida_import.xml.sample`.  After the files are updated:
* Confirm that the `galaxy_url` entry in `config.ini` is the correct url for your galaxy instance (including `https://`).
* Run `irida_import.py --config`.
* Restart your galaxy instance.

This should allow the tool to update the galaxy URL before redirecting to IRIDA.  Let us know how it goes!

**Comment by aknijn** [comment]
It works! The Galaxy version we're using is the 16.01. Probably in January we will update to the last 16.10 version. Really thanks a lot for the time and expertise, great job!

**Comment by tom114** [comment]
Glad to hear, thanks for working through the issue with us.  We'll be merging the fix into the main branches in the next while.

**Comment by tom114** [comment]
`https_fixes` branch has been merged into `development.
