### ISSUE TITLE
remove/change nametags option

### ISSUE THREAD

**Issue by mwalker64** [phac-nml/irida-galaxy-importer#25]
please change the irida importer to have the option to not create nametags when importing data to galaxy or remove the creation of nametags all together. This has caused history issues since the July 2020 update

**Comment by ericenns** [comment]
Closing this as it is not an issue with the irida-galaxy-importer but instead with galaxy. Please see https://github.com/galaxyproject/galaxy/issues/12065

**Comment by mwalker64** [comment]
The issue brought up here wasn't to fix the galaxy bug but change the importer to bypass it since there no sign of a fix on the galaxy side. Nametags are an option when importing and there should be an option not to have them in the first place.
