### ISSUE TITLE
Import permissions

### ISSUE THREAD

**Issue by aknijn** [phac-nml/irida-galaxy-importer#3]
I'm sorry to be a pain but the importer gives me an error now: 
Traceback (most recent call last):
  File "/clusterfs/galaxy/galaxy-dist/tools/irida_import/irida_import.py", line 816, in <module>
    token=args.token)
  File "/clusterfs/galaxy/galaxy-dist/tools/irida_import/irida_import.py", line 738, in import_to_galaxy
    self.library = self.get_first_or_make_lib(desired_lib_name, email)
  File "/clusterfs/galaxy/galaxy-dist/tools/irida_import/irida_import.py", line 201, in get_first_or_make_lib
    raise Exception(error)
Exception: No Galaxy role could be found for the email: 'www.xxx@yyy.zz', quitting

And before when the import worked, the data could not be used while the permissions on the files were set for the role workflow@yyy.zz which is the user created according to the specifications.

The only thing which I've tried to do in between the two situations, is creating the workflow@yyy.zz role which gave an error while the role already existed as private in the database.

**Comment by csieffert** [comment]
It looks like the email address associated with the Galaxy account differs from the email address used in the user account for IRIDA.  In order for the importer to work properly, the user importing the data must have the same email address (case-sensitive) associated with both their IRIDA and Galaxy accounts.

**Comment by ericenns** [comment]
One cause of this exception could be that the "Galaxy User Email" provided does not match the email of user clicking the "IRIDA" tool in galaxy. This email is case sensitive, and it is best practice to have this as the corresponding IRIDA user's email.

**Comment by aknijn** [comment]
OK, the error was mine: the accounts between Galaxy and Irida were the same but I had "downgraded" the workflow account to non-administrative on Galaxy and that caused the error. Now I'm back to the situation where I had the second problem: the files are imported fine but they can not be used while the permissions on them are set for the role workflow@yyy.zz. 
The error when I try to use them, is the following:
`The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool: User does not have permission to use a dataset (76965) provided for input.`
The permissions of the files are the following:
`    Users having associated role can import this dataset into their history for analysis.
        workflow@yyy.zz
    Users having associated role can manage the roles associated with permissions on this dataset.
        workflow@yyy.zz`
The json_parameter_file reports the email of the user account correctly, not the email of the workflow account.

**Comment by ericenns** [comment]
So just for clarification is the workflow@yyy.zzz the admin_key that is set in the tools yml config file?

**Comment by aknijn** [comment]
Yes

**Comment by ericenns** [comment]
Sorry for the delay,  but I think the problem is the default dataset permissions for your import user. Please update them as seen in the picture below and see if that corrects the issue.

![irida_import_user_permissions](https://cloud.githubusercontent.com/assets/492127/26252266/6692a35a-3c75-11e7-9b5a-57a3a6bfe79d.png)

**Comment by aknijn** [comment]
Great! That solved the problem, the permissions are set correctly now. Many thanks!
